<?php
/** @package WesleyProjetos::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProjetoMap.php");

/**
 * ProjetoDAO provides object-oriented access to the projeto table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WesleyProjetos::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProjetoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var int */
	public $Cliente;

	/** @var date */
	public $DataInicio;

	/** @var date */
	public $DataEntrega;

	/** @var float */
	public $Valor;

	/** @var string */
	public $Obs;

	/** @var enum */
	public $Prioridade;

	/** @var enum */
	public $Status;


	/**
	 * Returns a dataset of Atividade objects with matching Projeto
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAtividades($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "atv_pro", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Cliente
	 * @return Cliente
	 */
	public function GetCliente()
	{
		return $this->_phreezer->GetManyToOne($this, "proj_cli");
	}


}
?>